"""add new table team

Revision ID: 490d3fac8b7b
Revises: b2ebd7087dd6
Create Date: 2022-07-03 17:49:15.694883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490d3fac8b7b'
down_revision = 'b2ebd7087dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Teams')
    # ### end Alembic commands ###
