"""empty message

Revision ID: 52315ce2502b
Revises: 
Create Date: 2022-07-03 13:23:08.891074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52315ce2502b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('date_created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'date_created')
    # ### end Alembic commands ###
