"""add new table team

Revision ID: 609bdf411a1f
Revises: b68be28a3936
Create Date: 2022-07-03 18:00:43.259563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609bdf411a1f'
down_revision = 'b68be28a3936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Teams', sa.Column('user', sa.String(length=8), nullable=True))
    op.create_foreign_key(None, 'Teams', 'Users', ['user'], ['id'])
    op.drop_column('Teams', 'Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Teams', sa.Column('Users', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'Teams', type_='foreignkey')
    op.drop_column('Teams', 'user')
    # ### end Alembic commands ###
