"""add new table team

Revision ID: b68be28a3936
Revises: 56d0bf4122d2
Create Date: 2022-07-03 17:58:46.709332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68be28a3936'
down_revision = '56d0bf4122d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Teams', 'Users', ['Users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Teams', type_='foreignkey')
    # ### end Alembic commands ###
