"""add new table team

Revision ID: dc960d1e4508
Revises: 6abaf106b9f5
Create Date: 2022-07-03 18:09:35.388091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc960d1e4508'
down_revision = '6abaf106b9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Teams', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Teams', 'Users', ['user_id'], ['id'])
    op.drop_column('Teams', 'Users')
    op.drop_column('Teams', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Teams', sa.Column('user', sa.VARCHAR(length=8), nullable=True))
    op.add_column('Teams', sa.Column('Users', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'Teams', type_='foreignkey')
    op.drop_column('Teams', 'user_id')
    # ### end Alembic commands ###
