"""add new table team

Revision ID: e8930a32653b
Revises: c4144561a781
Create Date: 2022-07-03 18:18:24.148086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8930a32653b'
down_revision = 'c4144561a781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Teams', 'Users', ['user_id'], ['id'])
    op.drop_column('Teams', 'Users')
    op.drop_column('Teams', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Teams', sa.Column('user', sa.VARCHAR(length=8), nullable=True))
    op.add_column('Teams', sa.Column('Users', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'Teams', type_='foreignkey')
    # ### end Alembic commands ###
