"""empty message

Revision ID: e8c6ea6af91c
Revises: f881825ba246
Create Date: 2022-07-05 17:12:54.529774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c6ea6af91c'
down_revision = 'f881825ba246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.String(length=1000), nullable=True))
        # batch_op.create_foreign_key(None, 'Users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flag')

    # ### end Alembic commands ###
