"""empty message

Revision ID: f881825ba246
Revises: cb72dba051db
Create Date: 2022-07-05 14:09:12.600694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f881825ba246'
down_revision = 'cb72dba051db'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teams', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.String(length=1000), nullable=True))
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('Users')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(length=8), nullable=True))
        batch_op.add_column(sa.Column('Users', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flag')

    # ### end Alembic commands ###
